print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/ysw/StupidRabbit/TuziProject/Assets/saying hi.mb"`)
{		
	file -o "/Users/ysw/StupidRabbit/TuziProject/Assets/saying hi.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/ysw/StupidRabbit/TuziProject/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/ysw/StupidRabbit/TuziProject/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/ysw/StupidRabbit/TuziProject/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
